# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.11
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_ADMM', [dirname(__file__)])
        except ImportError:
            import _ADMM
            return _ADMM
        if fp is not None:
            try:
                _mod = imp.load_module('_ADMM', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _ADMM = swig_import_helper()
    del swig_import_helper
else:
    import _ADMM
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _ADMM.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _ADMM.SwigPyIterator_value(self)
    def incr(self, n=1): return _ADMM.SwigPyIterator_incr(self, n)
    def decr(self, n=1): return _ADMM.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _ADMM.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _ADMM.SwigPyIterator_equal(self, *args)
    def copy(self): return _ADMM.SwigPyIterator_copy(self)
    def next(self): return _ADMM.SwigPyIterator_next(self)
    def __next__(self): return _ADMM.SwigPyIterator___next__(self)
    def previous(self): return _ADMM.SwigPyIterator_previous(self)
    def advance(self, *args): return _ADMM.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _ADMM.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _ADMM.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _ADMM.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _ADMM.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _ADMM.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _ADMM.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _ADMM.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class ADMM(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ADMM, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ADMM, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _ADMM.new_ADMM()
        try: self.this.append(this)
        except: self.this = this
    def LoadNodes(self, *args): return _ADMM.ADMM_LoadNodes(self, *args)
    def LoadEdges(self, *args): return _ADMM.ADMM_LoadEdges(self, *args)
    def Solve(self): return _ADMM.ADMM_Solve(self)
    def get_node_x_vals(self): return _ADMM.ADMM_get_node_x_vals(self)
    def get_edge_z_vals(self): return _ADMM.ADMM_get_edge_z_vals(self)
    def get_edge_u_vals(self): return _ADMM.ADMM_get_edge_u_vals(self)
    __swig_destroy__ = _ADMM.delete_ADMM
    __del__ = lambda self : None;
ADMM_swigregister = _ADMM.ADMM_swigregister
ADMM_swigregister(ADMM)

class LinOpVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, LinOpVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, LinOpVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _ADMM.LinOpVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _ADMM.LinOpVector___nonzero__(self)
    def __bool__(self): return _ADMM.LinOpVector___bool__(self)
    def __len__(self): return _ADMM.LinOpVector___len__(self)
    def pop(self): return _ADMM.LinOpVector_pop(self)
    def __getslice__(self, *args): return _ADMM.LinOpVector___getslice__(self, *args)
    def __setslice__(self, *args): return _ADMM.LinOpVector___setslice__(self, *args)
    def __delslice__(self, *args): return _ADMM.LinOpVector___delslice__(self, *args)
    def __delitem__(self, *args): return _ADMM.LinOpVector___delitem__(self, *args)
    def __getitem__(self, *args): return _ADMM.LinOpVector___getitem__(self, *args)
    def __setitem__(self, *args): return _ADMM.LinOpVector___setitem__(self, *args)
    def append(self, *args): return _ADMM.LinOpVector_append(self, *args)
    def empty(self): return _ADMM.LinOpVector_empty(self)
    def size(self): return _ADMM.LinOpVector_size(self)
    def clear(self): return _ADMM.LinOpVector_clear(self)
    def swap(self, *args): return _ADMM.LinOpVector_swap(self, *args)
    def get_allocator(self): return _ADMM.LinOpVector_get_allocator(self)
    def begin(self): return _ADMM.LinOpVector_begin(self)
    def end(self): return _ADMM.LinOpVector_end(self)
    def rbegin(self): return _ADMM.LinOpVector_rbegin(self)
    def rend(self): return _ADMM.LinOpVector_rend(self)
    def pop_back(self): return _ADMM.LinOpVector_pop_back(self)
    def erase(self, *args): return _ADMM.LinOpVector_erase(self, *args)
    def __init__(self, *args): 
        this = _ADMM.new_LinOpVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _ADMM.LinOpVector_push_back(self, *args)
    def front(self): return _ADMM.LinOpVector_front(self)
    def back(self): return _ADMM.LinOpVector_back(self)
    def assign(self, *args): return _ADMM.LinOpVector_assign(self, *args)
    def resize(self, *args): return _ADMM.LinOpVector_resize(self, *args)
    def insert(self, *args): return _ADMM.LinOpVector_insert(self, *args)
    def reserve(self, *args): return _ADMM.LinOpVector_reserve(self, *args)
    def capacity(self): return _ADMM.LinOpVector_capacity(self)
    __swig_destroy__ = _ADMM.delete_LinOpVector
    __del__ = lambda self : None;
LinOpVector_swigregister = _ADMM.LinOpVector_swigregister
LinOpVector_swigregister(LinOpVector)

class LinOpVector2D(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, LinOpVector2D, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, LinOpVector2D, name)
    __repr__ = _swig_repr
    def iterator(self): return _ADMM.LinOpVector2D_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _ADMM.LinOpVector2D___nonzero__(self)
    def __bool__(self): return _ADMM.LinOpVector2D___bool__(self)
    def __len__(self): return _ADMM.LinOpVector2D___len__(self)
    def pop(self): return _ADMM.LinOpVector2D_pop(self)
    def __getslice__(self, *args): return _ADMM.LinOpVector2D___getslice__(self, *args)
    def __setslice__(self, *args): return _ADMM.LinOpVector2D___setslice__(self, *args)
    def __delslice__(self, *args): return _ADMM.LinOpVector2D___delslice__(self, *args)
    def __delitem__(self, *args): return _ADMM.LinOpVector2D___delitem__(self, *args)
    def __getitem__(self, *args): return _ADMM.LinOpVector2D___getitem__(self, *args)
    def __setitem__(self, *args): return _ADMM.LinOpVector2D___setitem__(self, *args)
    def append(self, *args): return _ADMM.LinOpVector2D_append(self, *args)
    def empty(self): return _ADMM.LinOpVector2D_empty(self)
    def size(self): return _ADMM.LinOpVector2D_size(self)
    def clear(self): return _ADMM.LinOpVector2D_clear(self)
    def swap(self, *args): return _ADMM.LinOpVector2D_swap(self, *args)
    def get_allocator(self): return _ADMM.LinOpVector2D_get_allocator(self)
    def begin(self): return _ADMM.LinOpVector2D_begin(self)
    def end(self): return _ADMM.LinOpVector2D_end(self)
    def rbegin(self): return _ADMM.LinOpVector2D_rbegin(self)
    def rend(self): return _ADMM.LinOpVector2D_rend(self)
    def pop_back(self): return _ADMM.LinOpVector2D_pop_back(self)
    def erase(self, *args): return _ADMM.LinOpVector2D_erase(self, *args)
    def __init__(self, *args): 
        this = _ADMM.new_LinOpVector2D(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _ADMM.LinOpVector2D_push_back(self, *args)
    def front(self): return _ADMM.LinOpVector2D_front(self)
    def back(self): return _ADMM.LinOpVector2D_back(self)
    def assign(self, *args): return _ADMM.LinOpVector2D_assign(self, *args)
    def resize(self, *args): return _ADMM.LinOpVector2D_resize(self, *args)
    def insert(self, *args): return _ADMM.LinOpVector2D_insert(self, *args)
    def reserve(self, *args): return _ADMM.LinOpVector2D_reserve(self, *args)
    def capacity(self): return _ADMM.LinOpVector2D_capacity(self)
    __swig_destroy__ = _ADMM.delete_LinOpVector2D
    __del__ = lambda self : None;
LinOpVector2D_swigregister = _ADMM.LinOpVector2D_swigregister
LinOpVector2D_swigregister(LinOpVector2D)

class solution(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, solution, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, solution, name)
    __repr__ = _swig_repr
    def iterator(self): return _ADMM.solution_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _ADMM.solution___nonzero__(self)
    def __bool__(self): return _ADMM.solution___bool__(self)
    def __len__(self): return _ADMM.solution___len__(self)
    def __iter__(self): return self.key_iterator()
    def iterkeys(self): return self.key_iterator()
    def itervalues(self): return self.value_iterator()
    def iteritems(self): return self.iterator()
    def __getitem__(self, *args): return _ADMM.solution___getitem__(self, *args)
    def __delitem__(self, *args): return _ADMM.solution___delitem__(self, *args)
    def has_key(self, *args): return _ADMM.solution_has_key(self, *args)
    def keys(self): return _ADMM.solution_keys(self)
    def values(self): return _ADMM.solution_values(self)
    def items(self): return _ADMM.solution_items(self)
    def __contains__(self, *args): return _ADMM.solution___contains__(self, *args)
    def key_iterator(self): return _ADMM.solution_key_iterator(self)
    def value_iterator(self): return _ADMM.solution_value_iterator(self)
    def __setitem__(self, *args): return _ADMM.solution___setitem__(self, *args)
    def asdict(self): return _ADMM.solution_asdict(self)
    def __init__(self, *args): 
        this = _ADMM.new_solution(*args)
        try: self.this.append(this)
        except: self.this = this
    def empty(self): return _ADMM.solution_empty(self)
    def size(self): return _ADMM.solution_size(self)
    def clear(self): return _ADMM.solution_clear(self)
    def swap(self, *args): return _ADMM.solution_swap(self, *args)
    def get_allocator(self): return _ADMM.solution_get_allocator(self)
    def begin(self): return _ADMM.solution_begin(self)
    def end(self): return _ADMM.solution_end(self)
    def rbegin(self): return _ADMM.solution_rbegin(self)
    def rend(self): return _ADMM.solution_rend(self)
    def count(self, *args): return _ADMM.solution_count(self, *args)
    def erase(self, *args): return _ADMM.solution_erase(self, *args)
    def find(self, *args): return _ADMM.solution_find(self, *args)
    def lower_bound(self, *args): return _ADMM.solution_lower_bound(self, *args)
    def upper_bound(self, *args): return _ADMM.solution_upper_bound(self, *args)
    __swig_destroy__ = _ADMM.delete_solution
    __del__ = lambda self : None;
solution_swigregister = _ADMM.solution_swigregister
solution_swigregister(solution)

class solutionVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, solutionVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, solutionVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _ADMM.solutionVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _ADMM.solutionVector___nonzero__(self)
    def __bool__(self): return _ADMM.solutionVector___bool__(self)
    def __len__(self): return _ADMM.solutionVector___len__(self)
    def pop(self): return _ADMM.solutionVector_pop(self)
    def __getslice__(self, *args): return _ADMM.solutionVector___getslice__(self, *args)
    def __setslice__(self, *args): return _ADMM.solutionVector___setslice__(self, *args)
    def __delslice__(self, *args): return _ADMM.solutionVector___delslice__(self, *args)
    def __delitem__(self, *args): return _ADMM.solutionVector___delitem__(self, *args)
    def __getitem__(self, *args): return _ADMM.solutionVector___getitem__(self, *args)
    def __setitem__(self, *args): return _ADMM.solutionVector___setitem__(self, *args)
    def append(self, *args): return _ADMM.solutionVector_append(self, *args)
    def empty(self): return _ADMM.solutionVector_empty(self)
    def size(self): return _ADMM.solutionVector_size(self)
    def clear(self): return _ADMM.solutionVector_clear(self)
    def swap(self, *args): return _ADMM.solutionVector_swap(self, *args)
    def get_allocator(self): return _ADMM.solutionVector_get_allocator(self)
    def begin(self): return _ADMM.solutionVector_begin(self)
    def end(self): return _ADMM.solutionVector_end(self)
    def rbegin(self): return _ADMM.solutionVector_rbegin(self)
    def rend(self): return _ADMM.solutionVector_rend(self)
    def pop_back(self): return _ADMM.solutionVector_pop_back(self)
    def erase(self, *args): return _ADMM.solutionVector_erase(self, *args)
    def __init__(self, *args): 
        this = _ADMM.new_solutionVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _ADMM.solutionVector_push_back(self, *args)
    def front(self): return _ADMM.solutionVector_front(self)
    def back(self): return _ADMM.solutionVector_back(self)
    def assign(self, *args): return _ADMM.solutionVector_assign(self, *args)
    def resize(self, *args): return _ADMM.solutionVector_resize(self, *args)
    def insert(self, *args): return _ADMM.solutionVector_insert(self, *args)
    def reserve(self, *args): return _ADMM.solutionVector_reserve(self, *args)
    def capacity(self): return _ADMM.solutionVector_capacity(self)
    __swig_destroy__ = _ADMM.delete_solutionVector
    __del__ = lambda self : None;
solutionVector_swigregister = _ADMM.solutionVector_swigregister
solutionVector_swigregister(solutionVector)

# This file is compatible with both classic and new-style classes.


