# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.11
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_ADMM', [dirname(__file__)])
        except ImportError:
            import _ADMM
            return _ADMM
        if fp is not None:
            try:
                _mod = imp.load_module('_ADMM', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _ADMM = swig_import_helper()
    del swig_import_helper
else:
    import _ADMM
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _ADMM.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _ADMM.SwigPyIterator_value(self)
    def incr(self, n=1): return _ADMM.SwigPyIterator_incr(self, n)
    def decr(self, n=1): return _ADMM.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _ADMM.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _ADMM.SwigPyIterator_equal(self, *args)
    def copy(self): return _ADMM.SwigPyIterator_copy(self)
    def next(self): return _ADMM.SwigPyIterator_next(self)
    def __next__(self): return _ADMM.SwigPyIterator___next__(self)
    def previous(self): return _ADMM.SwigPyIterator_previous(self)
    def advance(self, *args): return _ADMM.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _ADMM.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _ADMM.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _ADMM.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _ADMM.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _ADMM.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _ADMM.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _ADMM.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

SQUARE = _ADMM.SQUARE
LASSO = _ADMM.LASSO
NONE = _ADMM.NONE
class Node(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Node, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Node, name)
    __repr__ = _swig_repr
    __swig_setmethods__["node_objective"] = _ADMM.Node_node_objective_set
    __swig_getmethods__["node_objective"] = _ADMM.Node_node_objective_get
    if _newclass:node_objective = _swig_property(_ADMM.Node_node_objective_get, _ADMM.Node_node_objective_set)
    __swig_setmethods__["node_constraints"] = _ADMM.Node_node_constraints_set
    __swig_getmethods__["node_constraints"] = _ADMM.Node_node_constraints_get
    if _newclass:node_constraints = _swig_property(_ADMM.Node_node_constraints_get, _ADMM.Node_node_constraints_set)
    __swig_setmethods__["neighbour_var_idx"] = _ADMM.Node_neighbour_var_idx_set
    __swig_getmethods__["neighbour_var_idx"] = _ADMM.Node_neighbour_var_idx_get
    if _newclass:neighbour_var_idx = _swig_property(_ADMM.Node_neighbour_var_idx_get, _ADMM.Node_neighbour_var_idx_set)
    __swig_setmethods__["x_var_idx"] = _ADMM.Node_x_var_idx_set
    __swig_getmethods__["x_var_idx"] = _ADMM.Node_x_var_idx_get
    if _newclass:x_var_idx = _swig_property(_ADMM.Node_x_var_idx_get, _ADMM.Node_x_var_idx_set)
    __swig_setmethods__["args"] = _ADMM.Node_args_set
    __swig_getmethods__["args"] = _ADMM.Node_args_get
    if _newclass:args = _swig_property(_ADMM.Node_args_get, _ADMM.Node_args_set)
    def __init__(self): 
        this = _ADMM.new_Node()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ADMM.delete_Node
    __del__ = lambda self : None;
Node_swigregister = _ADMM.Node_swigregister
Node_swigregister(Node)

class Edge(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Edge, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Edge, name)
    __repr__ = _swig_repr
    __swig_setmethods__["edge_objective"] = _ADMM.Edge_edge_objective_set
    __swig_getmethods__["edge_objective"] = _ADMM.Edge_edge_objective_get
    if _newclass:edge_objective = _swig_property(_ADMM.Edge_edge_objective_get, _ADMM.Edge_edge_objective_set)
    __swig_setmethods__["edge_constraints"] = _ADMM.Edge_edge_constraints_set
    __swig_getmethods__["edge_constraints"] = _ADMM.Edge_edge_constraints_get
    if _newclass:edge_constraints = _swig_property(_ADMM.Edge_edge_constraints_get, _ADMM.Edge_edge_constraints_set)
    __swig_setmethods__["edge_var_idx_left"] = _ADMM.Edge_edge_var_idx_left_set
    __swig_getmethods__["edge_var_idx_left"] = _ADMM.Edge_edge_var_idx_left_get
    if _newclass:edge_var_idx_left = _swig_property(_ADMM.Edge_edge_var_idx_left_get, _ADMM.Edge_edge_var_idx_left_set)
    __swig_setmethods__["edge_var_idx_right"] = _ADMM.Edge_edge_var_idx_right_set
    __swig_getmethods__["edge_var_idx_right"] = _ADMM.Edge_edge_var_idx_right_get
    if _newclass:edge_var_idx_right = _swig_property(_ADMM.Edge_edge_var_idx_right_get, _ADMM.Edge_edge_var_idx_right_set)
    __swig_setmethods__["node_var_idx_left"] = _ADMM.Edge_node_var_idx_left_set
    __swig_getmethods__["node_var_idx_left"] = _ADMM.Edge_node_var_idx_left_get
    if _newclass:node_var_idx_left = _swig_property(_ADMM.Edge_node_var_idx_left_get, _ADMM.Edge_node_var_idx_left_set)
    __swig_setmethods__["node_var_idx_right"] = _ADMM.Edge_node_var_idx_right_set
    __swig_getmethods__["node_var_idx_right"] = _ADMM.Edge_node_var_idx_right_get
    if _newclass:node_var_idx_right = _swig_property(_ADMM.Edge_node_var_idx_right_get, _ADMM.Edge_node_var_idx_right_set)
    def __init__(self): 
        this = _ADMM.new_Edge()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ADMM.delete_Edge
    __del__ = lambda self : None;
Edge_swigregister = _ADMM.Edge_swigregister
Edge_swigregister(Edge)

class Node_Var(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Node_Var, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Node_Var, name)
    __repr__ = _swig_repr
    __swig_setmethods__["value"] = _ADMM.Node_Var_value_set
    __swig_getmethods__["value"] = _ADMM.Node_Var_value_get
    if _newclass:value = _swig_property(_ADMM.Node_Var_value_get, _ADMM.Node_Var_value_set)
    __swig_setmethods__["name"] = _ADMM.Node_Var_name_set
    __swig_getmethods__["name"] = _ADMM.Node_Var_name_get
    if _newclass:name = _swig_property(_ADMM.Node_Var_name_get, _ADMM.Node_Var_name_set)
    __swig_setmethods__["nodeId"] = _ADMM.Node_Var_nodeId_set
    __swig_getmethods__["nodeId"] = _ADMM.Node_Var_nodeId_get
    if _newclass:nodeId = _swig_property(_ADMM.Node_Var_nodeId_get, _ADMM.Node_Var_nodeId_set)
    def __init__(self): 
        this = _ADMM.new_Node_Var()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _ADMM.delete_Node_Var
    __del__ = lambda self : None;
Node_Var_swigregister = _ADMM.Node_Var_swigregister
Node_Var_swigregister(Node_Var)

class ADMM(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ADMM, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ADMM, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _ADMM.new_ADMM()
        try: self.this.append(this)
        except: self.this = this
    def LoadNodes(self, *args): return _ADMM.ADMM_LoadNodes(self, *args)
    def LoadEdges(self, *args): return _ADMM.ADMM_LoadEdges(self, *args)
    def LoadNodesProximal(self, *args): return _ADMM.ADMM_LoadNodesProximal(self, *args)
    def LoadEdgesProximal(self, *args): return _ADMM.ADMM_LoadEdgesProximal(self, *args)
    def LoadNodeProximal(self, *args): return _ADMM.ADMM_LoadNodeProximal(self, *args)
    def LoadEdgeProximal(self, *args): return _ADMM.ADMM_LoadEdgeProximal(self, *args)
    def Solve(self): return _ADMM.ADMM_Solve(self)
    def PrintSolution(self): return _ADMM.ADMM_PrintSolution(self)
    def numpyToVector(self, *args): return _ADMM.ADMM_numpyToVector(self, *args)
    __swig_destroy__ = _ADMM.delete_ADMM
    __del__ = lambda self : None;
ADMM_swigregister = _ADMM.ADMM_swigregister
ADMM_swigregister(ADMM)

class StringVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, StringVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, StringVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _ADMM.StringVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _ADMM.StringVector___nonzero__(self)
    def __bool__(self): return _ADMM.StringVector___bool__(self)
    def __len__(self): return _ADMM.StringVector___len__(self)
    def pop(self): return _ADMM.StringVector_pop(self)
    def __getslice__(self, *args): return _ADMM.StringVector___getslice__(self, *args)
    def __setslice__(self, *args): return _ADMM.StringVector___setslice__(self, *args)
    def __delslice__(self, *args): return _ADMM.StringVector___delslice__(self, *args)
    def __delitem__(self, *args): return _ADMM.StringVector___delitem__(self, *args)
    def __getitem__(self, *args): return _ADMM.StringVector___getitem__(self, *args)
    def __setitem__(self, *args): return _ADMM.StringVector___setitem__(self, *args)
    def append(self, *args): return _ADMM.StringVector_append(self, *args)
    def empty(self): return _ADMM.StringVector_empty(self)
    def size(self): return _ADMM.StringVector_size(self)
    def clear(self): return _ADMM.StringVector_clear(self)
    def swap(self, *args): return _ADMM.StringVector_swap(self, *args)
    def get_allocator(self): return _ADMM.StringVector_get_allocator(self)
    def begin(self): return _ADMM.StringVector_begin(self)
    def end(self): return _ADMM.StringVector_end(self)
    def rbegin(self): return _ADMM.StringVector_rbegin(self)
    def rend(self): return _ADMM.StringVector_rend(self)
    def pop_back(self): return _ADMM.StringVector_pop_back(self)
    def erase(self, *args): return _ADMM.StringVector_erase(self, *args)
    def __init__(self, *args): 
        this = _ADMM.new_StringVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _ADMM.StringVector_push_back(self, *args)
    def front(self): return _ADMM.StringVector_front(self)
    def back(self): return _ADMM.StringVector_back(self)
    def assign(self, *args): return _ADMM.StringVector_assign(self, *args)
    def resize(self, *args): return _ADMM.StringVector_resize(self, *args)
    def insert(self, *args): return _ADMM.StringVector_insert(self, *args)
    def reserve(self, *args): return _ADMM.StringVector_reserve(self, *args)
    def capacity(self): return _ADMM.StringVector_capacity(self)
    __swig_destroy__ = _ADMM.delete_StringVector
    __del__ = lambda self : None;
StringVector_swigregister = _ADMM.StringVector_swigregister
StringVector_swigregister(StringVector)

class StringVector2D(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, StringVector2D, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, StringVector2D, name)
    __repr__ = _swig_repr
    def iterator(self): return _ADMM.StringVector2D_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _ADMM.StringVector2D___nonzero__(self)
    def __bool__(self): return _ADMM.StringVector2D___bool__(self)
    def __len__(self): return _ADMM.StringVector2D___len__(self)
    def pop(self): return _ADMM.StringVector2D_pop(self)
    def __getslice__(self, *args): return _ADMM.StringVector2D___getslice__(self, *args)
    def __setslice__(self, *args): return _ADMM.StringVector2D___setslice__(self, *args)
    def __delslice__(self, *args): return _ADMM.StringVector2D___delslice__(self, *args)
    def __delitem__(self, *args): return _ADMM.StringVector2D___delitem__(self, *args)
    def __getitem__(self, *args): return _ADMM.StringVector2D___getitem__(self, *args)
    def __setitem__(self, *args): return _ADMM.StringVector2D___setitem__(self, *args)
    def append(self, *args): return _ADMM.StringVector2D_append(self, *args)
    def empty(self): return _ADMM.StringVector2D_empty(self)
    def size(self): return _ADMM.StringVector2D_size(self)
    def clear(self): return _ADMM.StringVector2D_clear(self)
    def swap(self, *args): return _ADMM.StringVector2D_swap(self, *args)
    def get_allocator(self): return _ADMM.StringVector2D_get_allocator(self)
    def begin(self): return _ADMM.StringVector2D_begin(self)
    def end(self): return _ADMM.StringVector2D_end(self)
    def rbegin(self): return _ADMM.StringVector2D_rbegin(self)
    def rend(self): return _ADMM.StringVector2D_rend(self)
    def pop_back(self): return _ADMM.StringVector2D_pop_back(self)
    def erase(self, *args): return _ADMM.StringVector2D_erase(self, *args)
    def __init__(self, *args): 
        this = _ADMM.new_StringVector2D(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _ADMM.StringVector2D_push_back(self, *args)
    def front(self): return _ADMM.StringVector2D_front(self)
    def back(self): return _ADMM.StringVector2D_back(self)
    def assign(self, *args): return _ADMM.StringVector2D_assign(self, *args)
    def resize(self, *args): return _ADMM.StringVector2D_resize(self, *args)
    def insert(self, *args): return _ADMM.StringVector2D_insert(self, *args)
    def reserve(self, *args): return _ADMM.StringVector2D_reserve(self, *args)
    def capacity(self): return _ADMM.StringVector2D_capacity(self)
    __swig_destroy__ = _ADMM.delete_StringVector2D
    __del__ = lambda self : None;
StringVector2D_swigregister = _ADMM.StringVector2D_swigregister
StringVector2D_swigregister(StringVector2D)

class IntVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IntVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IntVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _ADMM.IntVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _ADMM.IntVector___nonzero__(self)
    def __bool__(self): return _ADMM.IntVector___bool__(self)
    def __len__(self): return _ADMM.IntVector___len__(self)
    def pop(self): return _ADMM.IntVector_pop(self)
    def __getslice__(self, *args): return _ADMM.IntVector___getslice__(self, *args)
    def __setslice__(self, *args): return _ADMM.IntVector___setslice__(self, *args)
    def __delslice__(self, *args): return _ADMM.IntVector___delslice__(self, *args)
    def __delitem__(self, *args): return _ADMM.IntVector___delitem__(self, *args)
    def __getitem__(self, *args): return _ADMM.IntVector___getitem__(self, *args)
    def __setitem__(self, *args): return _ADMM.IntVector___setitem__(self, *args)
    def append(self, *args): return _ADMM.IntVector_append(self, *args)
    def empty(self): return _ADMM.IntVector_empty(self)
    def size(self): return _ADMM.IntVector_size(self)
    def clear(self): return _ADMM.IntVector_clear(self)
    def swap(self, *args): return _ADMM.IntVector_swap(self, *args)
    def get_allocator(self): return _ADMM.IntVector_get_allocator(self)
    def begin(self): return _ADMM.IntVector_begin(self)
    def end(self): return _ADMM.IntVector_end(self)
    def rbegin(self): return _ADMM.IntVector_rbegin(self)
    def rend(self): return _ADMM.IntVector_rend(self)
    def pop_back(self): return _ADMM.IntVector_pop_back(self)
    def erase(self, *args): return _ADMM.IntVector_erase(self, *args)
    def __init__(self, *args): 
        this = _ADMM.new_IntVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _ADMM.IntVector_push_back(self, *args)
    def front(self): return _ADMM.IntVector_front(self)
    def back(self): return _ADMM.IntVector_back(self)
    def assign(self, *args): return _ADMM.IntVector_assign(self, *args)
    def resize(self, *args): return _ADMM.IntVector_resize(self, *args)
    def insert(self, *args): return _ADMM.IntVector_insert(self, *args)
    def reserve(self, *args): return _ADMM.IntVector_reserve(self, *args)
    def capacity(self): return _ADMM.IntVector_capacity(self)
    __swig_destroy__ = _ADMM.delete_IntVector
    __del__ = lambda self : None;
IntVector_swigregister = _ADMM.IntVector_swigregister
IntVector_swigregister(IntVector)

class IntVector2D(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IntVector2D, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IntVector2D, name)
    __repr__ = _swig_repr
    def iterator(self): return _ADMM.IntVector2D_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _ADMM.IntVector2D___nonzero__(self)
    def __bool__(self): return _ADMM.IntVector2D___bool__(self)
    def __len__(self): return _ADMM.IntVector2D___len__(self)
    def pop(self): return _ADMM.IntVector2D_pop(self)
    def __getslice__(self, *args): return _ADMM.IntVector2D___getslice__(self, *args)
    def __setslice__(self, *args): return _ADMM.IntVector2D___setslice__(self, *args)
    def __delslice__(self, *args): return _ADMM.IntVector2D___delslice__(self, *args)
    def __delitem__(self, *args): return _ADMM.IntVector2D___delitem__(self, *args)
    def __getitem__(self, *args): return _ADMM.IntVector2D___getitem__(self, *args)
    def __setitem__(self, *args): return _ADMM.IntVector2D___setitem__(self, *args)
    def append(self, *args): return _ADMM.IntVector2D_append(self, *args)
    def empty(self): return _ADMM.IntVector2D_empty(self)
    def size(self): return _ADMM.IntVector2D_size(self)
    def clear(self): return _ADMM.IntVector2D_clear(self)
    def swap(self, *args): return _ADMM.IntVector2D_swap(self, *args)
    def get_allocator(self): return _ADMM.IntVector2D_get_allocator(self)
    def begin(self): return _ADMM.IntVector2D_begin(self)
    def end(self): return _ADMM.IntVector2D_end(self)
    def rbegin(self): return _ADMM.IntVector2D_rbegin(self)
    def rend(self): return _ADMM.IntVector2D_rend(self)
    def pop_back(self): return _ADMM.IntVector2D_pop_back(self)
    def erase(self, *args): return _ADMM.IntVector2D_erase(self, *args)
    def __init__(self, *args): 
        this = _ADMM.new_IntVector2D(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _ADMM.IntVector2D_push_back(self, *args)
    def front(self): return _ADMM.IntVector2D_front(self)
    def back(self): return _ADMM.IntVector2D_back(self)
    def assign(self, *args): return _ADMM.IntVector2D_assign(self, *args)
    def resize(self, *args): return _ADMM.IntVector2D_resize(self, *args)
    def insert(self, *args): return _ADMM.IntVector2D_insert(self, *args)
    def reserve(self, *args): return _ADMM.IntVector2D_reserve(self, *args)
    def capacity(self): return _ADMM.IntVector2D_capacity(self)
    __swig_destroy__ = _ADMM.delete_IntVector2D
    __del__ = lambda self : None;
IntVector2D_swigregister = _ADMM.IntVector2D_swigregister
IntVector2D_swigregister(IntVector2D)

class IntVector3D(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IntVector3D, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IntVector3D, name)
    __repr__ = _swig_repr
    def iterator(self): return _ADMM.IntVector3D_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _ADMM.IntVector3D___nonzero__(self)
    def __bool__(self): return _ADMM.IntVector3D___bool__(self)
    def __len__(self): return _ADMM.IntVector3D___len__(self)
    def pop(self): return _ADMM.IntVector3D_pop(self)
    def __getslice__(self, *args): return _ADMM.IntVector3D___getslice__(self, *args)
    def __setslice__(self, *args): return _ADMM.IntVector3D___setslice__(self, *args)
    def __delslice__(self, *args): return _ADMM.IntVector3D___delslice__(self, *args)
    def __delitem__(self, *args): return _ADMM.IntVector3D___delitem__(self, *args)
    def __getitem__(self, *args): return _ADMM.IntVector3D___getitem__(self, *args)
    def __setitem__(self, *args): return _ADMM.IntVector3D___setitem__(self, *args)
    def append(self, *args): return _ADMM.IntVector3D_append(self, *args)
    def empty(self): return _ADMM.IntVector3D_empty(self)
    def size(self): return _ADMM.IntVector3D_size(self)
    def clear(self): return _ADMM.IntVector3D_clear(self)
    def swap(self, *args): return _ADMM.IntVector3D_swap(self, *args)
    def get_allocator(self): return _ADMM.IntVector3D_get_allocator(self)
    def begin(self): return _ADMM.IntVector3D_begin(self)
    def end(self): return _ADMM.IntVector3D_end(self)
    def rbegin(self): return _ADMM.IntVector3D_rbegin(self)
    def rend(self): return _ADMM.IntVector3D_rend(self)
    def pop_back(self): return _ADMM.IntVector3D_pop_back(self)
    def erase(self, *args): return _ADMM.IntVector3D_erase(self, *args)
    def __init__(self, *args): 
        this = _ADMM.new_IntVector3D(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _ADMM.IntVector3D_push_back(self, *args)
    def front(self): return _ADMM.IntVector3D_front(self)
    def back(self): return _ADMM.IntVector3D_back(self)
    def assign(self, *args): return _ADMM.IntVector3D_assign(self, *args)
    def resize(self, *args): return _ADMM.IntVector3D_resize(self, *args)
    def insert(self, *args): return _ADMM.IntVector3D_insert(self, *args)
    def reserve(self, *args): return _ADMM.IntVector3D_reserve(self, *args)
    def capacity(self): return _ADMM.IntVector3D_capacity(self)
    __swig_destroy__ = _ADMM.delete_IntVector3D
    __del__ = lambda self : None;
IntVector3D_swigregister = _ADMM.IntVector3D_swigregister
IntVector3D_swigregister(IntVector3D)

class DoubleVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DoubleVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DoubleVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _ADMM.DoubleVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _ADMM.DoubleVector___nonzero__(self)
    def __bool__(self): return _ADMM.DoubleVector___bool__(self)
    def __len__(self): return _ADMM.DoubleVector___len__(self)
    def pop(self): return _ADMM.DoubleVector_pop(self)
    def __getslice__(self, *args): return _ADMM.DoubleVector___getslice__(self, *args)
    def __setslice__(self, *args): return _ADMM.DoubleVector___setslice__(self, *args)
    def __delslice__(self, *args): return _ADMM.DoubleVector___delslice__(self, *args)
    def __delitem__(self, *args): return _ADMM.DoubleVector___delitem__(self, *args)
    def __getitem__(self, *args): return _ADMM.DoubleVector___getitem__(self, *args)
    def __setitem__(self, *args): return _ADMM.DoubleVector___setitem__(self, *args)
    def append(self, *args): return _ADMM.DoubleVector_append(self, *args)
    def empty(self): return _ADMM.DoubleVector_empty(self)
    def size(self): return _ADMM.DoubleVector_size(self)
    def clear(self): return _ADMM.DoubleVector_clear(self)
    def swap(self, *args): return _ADMM.DoubleVector_swap(self, *args)
    def get_allocator(self): return _ADMM.DoubleVector_get_allocator(self)
    def begin(self): return _ADMM.DoubleVector_begin(self)
    def end(self): return _ADMM.DoubleVector_end(self)
    def rbegin(self): return _ADMM.DoubleVector_rbegin(self)
    def rend(self): return _ADMM.DoubleVector_rend(self)
    def pop_back(self): return _ADMM.DoubleVector_pop_back(self)
    def erase(self, *args): return _ADMM.DoubleVector_erase(self, *args)
    def __init__(self, *args): 
        this = _ADMM.new_DoubleVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _ADMM.DoubleVector_push_back(self, *args)
    def front(self): return _ADMM.DoubleVector_front(self)
    def back(self): return _ADMM.DoubleVector_back(self)
    def assign(self, *args): return _ADMM.DoubleVector_assign(self, *args)
    def resize(self, *args): return _ADMM.DoubleVector_resize(self, *args)
    def insert(self, *args): return _ADMM.DoubleVector_insert(self, *args)
    def reserve(self, *args): return _ADMM.DoubleVector_reserve(self, *args)
    def capacity(self): return _ADMM.DoubleVector_capacity(self)
    __swig_destroy__ = _ADMM.delete_DoubleVector
    __del__ = lambda self : None;
DoubleVector_swigregister = _ADMM.DoubleVector_swigregister
DoubleVector_swigregister(DoubleVector)

class DoubleVector2D(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DoubleVector2D, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DoubleVector2D, name)
    __repr__ = _swig_repr
    def iterator(self): return _ADMM.DoubleVector2D_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _ADMM.DoubleVector2D___nonzero__(self)
    def __bool__(self): return _ADMM.DoubleVector2D___bool__(self)
    def __len__(self): return _ADMM.DoubleVector2D___len__(self)
    def pop(self): return _ADMM.DoubleVector2D_pop(self)
    def __getslice__(self, *args): return _ADMM.DoubleVector2D___getslice__(self, *args)
    def __setslice__(self, *args): return _ADMM.DoubleVector2D___setslice__(self, *args)
    def __delslice__(self, *args): return _ADMM.DoubleVector2D___delslice__(self, *args)
    def __delitem__(self, *args): return _ADMM.DoubleVector2D___delitem__(self, *args)
    def __getitem__(self, *args): return _ADMM.DoubleVector2D___getitem__(self, *args)
    def __setitem__(self, *args): return _ADMM.DoubleVector2D___setitem__(self, *args)
    def append(self, *args): return _ADMM.DoubleVector2D_append(self, *args)
    def empty(self): return _ADMM.DoubleVector2D_empty(self)
    def size(self): return _ADMM.DoubleVector2D_size(self)
    def clear(self): return _ADMM.DoubleVector2D_clear(self)
    def swap(self, *args): return _ADMM.DoubleVector2D_swap(self, *args)
    def get_allocator(self): return _ADMM.DoubleVector2D_get_allocator(self)
    def begin(self): return _ADMM.DoubleVector2D_begin(self)
    def end(self): return _ADMM.DoubleVector2D_end(self)
    def rbegin(self): return _ADMM.DoubleVector2D_rbegin(self)
    def rend(self): return _ADMM.DoubleVector2D_rend(self)
    def pop_back(self): return _ADMM.DoubleVector2D_pop_back(self)
    def erase(self, *args): return _ADMM.DoubleVector2D_erase(self, *args)
    def __init__(self, *args): 
        this = _ADMM.new_DoubleVector2D(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _ADMM.DoubleVector2D_push_back(self, *args)
    def front(self): return _ADMM.DoubleVector2D_front(self)
    def back(self): return _ADMM.DoubleVector2D_back(self)
    def assign(self, *args): return _ADMM.DoubleVector2D_assign(self, *args)
    def resize(self, *args): return _ADMM.DoubleVector2D_resize(self, *args)
    def insert(self, *args): return _ADMM.DoubleVector2D_insert(self, *args)
    def reserve(self, *args): return _ADMM.DoubleVector2D_reserve(self, *args)
    def capacity(self): return _ADMM.DoubleVector2D_capacity(self)
    __swig_destroy__ = _ADMM.delete_DoubleVector2D
    __del__ = lambda self : None;
DoubleVector2D_swigregister = _ADMM.DoubleVector2D_swigregister
DoubleVector2D_swigregister(DoubleVector2D)

class DoubleVector3D(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DoubleVector3D, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DoubleVector3D, name)
    __repr__ = _swig_repr
    def iterator(self): return _ADMM.DoubleVector3D_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _ADMM.DoubleVector3D___nonzero__(self)
    def __bool__(self): return _ADMM.DoubleVector3D___bool__(self)
    def __len__(self): return _ADMM.DoubleVector3D___len__(self)
    def pop(self): return _ADMM.DoubleVector3D_pop(self)
    def __getslice__(self, *args): return _ADMM.DoubleVector3D___getslice__(self, *args)
    def __setslice__(self, *args): return _ADMM.DoubleVector3D___setslice__(self, *args)
    def __delslice__(self, *args): return _ADMM.DoubleVector3D___delslice__(self, *args)
    def __delitem__(self, *args): return _ADMM.DoubleVector3D___delitem__(self, *args)
    def __getitem__(self, *args): return _ADMM.DoubleVector3D___getitem__(self, *args)
    def __setitem__(self, *args): return _ADMM.DoubleVector3D___setitem__(self, *args)
    def append(self, *args): return _ADMM.DoubleVector3D_append(self, *args)
    def empty(self): return _ADMM.DoubleVector3D_empty(self)
    def size(self): return _ADMM.DoubleVector3D_size(self)
    def clear(self): return _ADMM.DoubleVector3D_clear(self)
    def swap(self, *args): return _ADMM.DoubleVector3D_swap(self, *args)
    def get_allocator(self): return _ADMM.DoubleVector3D_get_allocator(self)
    def begin(self): return _ADMM.DoubleVector3D_begin(self)
    def end(self): return _ADMM.DoubleVector3D_end(self)
    def rbegin(self): return _ADMM.DoubleVector3D_rbegin(self)
    def rend(self): return _ADMM.DoubleVector3D_rend(self)
    def pop_back(self): return _ADMM.DoubleVector3D_pop_back(self)
    def erase(self, *args): return _ADMM.DoubleVector3D_erase(self, *args)
    def __init__(self, *args): 
        this = _ADMM.new_DoubleVector3D(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _ADMM.DoubleVector3D_push_back(self, *args)
    def front(self): return _ADMM.DoubleVector3D_front(self)
    def back(self): return _ADMM.DoubleVector3D_back(self)
    def assign(self, *args): return _ADMM.DoubleVector3D_assign(self, *args)
    def resize(self, *args): return _ADMM.DoubleVector3D_resize(self, *args)
    def insert(self, *args): return _ADMM.DoubleVector3D_insert(self, *args)
    def reserve(self, *args): return _ADMM.DoubleVector3D_reserve(self, *args)
    def capacity(self): return _ADMM.DoubleVector3D_capacity(self)
    __swig_destroy__ = _ADMM.delete_DoubleVector3D
    __del__ = lambda self : None;
DoubleVector3D_swigregister = _ADMM.DoubleVector3D_swigregister
DoubleVector3D_swigregister(DoubleVector3D)

class LinOpVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, LinOpVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, LinOpVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _ADMM.LinOpVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _ADMM.LinOpVector___nonzero__(self)
    def __bool__(self): return _ADMM.LinOpVector___bool__(self)
    def __len__(self): return _ADMM.LinOpVector___len__(self)
    def pop(self): return _ADMM.LinOpVector_pop(self)
    def __getslice__(self, *args): return _ADMM.LinOpVector___getslice__(self, *args)
    def __setslice__(self, *args): return _ADMM.LinOpVector___setslice__(self, *args)
    def __delslice__(self, *args): return _ADMM.LinOpVector___delslice__(self, *args)
    def __delitem__(self, *args): return _ADMM.LinOpVector___delitem__(self, *args)
    def __getitem__(self, *args): return _ADMM.LinOpVector___getitem__(self, *args)
    def __setitem__(self, *args): return _ADMM.LinOpVector___setitem__(self, *args)
    def append(self, *args): return _ADMM.LinOpVector_append(self, *args)
    def empty(self): return _ADMM.LinOpVector_empty(self)
    def size(self): return _ADMM.LinOpVector_size(self)
    def clear(self): return _ADMM.LinOpVector_clear(self)
    def swap(self, *args): return _ADMM.LinOpVector_swap(self, *args)
    def get_allocator(self): return _ADMM.LinOpVector_get_allocator(self)
    def begin(self): return _ADMM.LinOpVector_begin(self)
    def end(self): return _ADMM.LinOpVector_end(self)
    def rbegin(self): return _ADMM.LinOpVector_rbegin(self)
    def rend(self): return _ADMM.LinOpVector_rend(self)
    def pop_back(self): return _ADMM.LinOpVector_pop_back(self)
    def erase(self, *args): return _ADMM.LinOpVector_erase(self, *args)
    def __init__(self, *args): 
        this = _ADMM.new_LinOpVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _ADMM.LinOpVector_push_back(self, *args)
    def front(self): return _ADMM.LinOpVector_front(self)
    def back(self): return _ADMM.LinOpVector_back(self)
    def assign(self, *args): return _ADMM.LinOpVector_assign(self, *args)
    def resize(self, *args): return _ADMM.LinOpVector_resize(self, *args)
    def insert(self, *args): return _ADMM.LinOpVector_insert(self, *args)
    def reserve(self, *args): return _ADMM.LinOpVector_reserve(self, *args)
    def capacity(self): return _ADMM.LinOpVector_capacity(self)
    __swig_destroy__ = _ADMM.delete_LinOpVector
    __del__ = lambda self : None;
LinOpVector_swigregister = _ADMM.LinOpVector_swigregister
LinOpVector_swigregister(LinOpVector)

class LinOpVector2D(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, LinOpVector2D, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, LinOpVector2D, name)
    __repr__ = _swig_repr
    def iterator(self): return _ADMM.LinOpVector2D_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _ADMM.LinOpVector2D___nonzero__(self)
    def __bool__(self): return _ADMM.LinOpVector2D___bool__(self)
    def __len__(self): return _ADMM.LinOpVector2D___len__(self)
    def pop(self): return _ADMM.LinOpVector2D_pop(self)
    def __getslice__(self, *args): return _ADMM.LinOpVector2D___getslice__(self, *args)
    def __setslice__(self, *args): return _ADMM.LinOpVector2D___setslice__(self, *args)
    def __delslice__(self, *args): return _ADMM.LinOpVector2D___delslice__(self, *args)
    def __delitem__(self, *args): return _ADMM.LinOpVector2D___delitem__(self, *args)
    def __getitem__(self, *args): return _ADMM.LinOpVector2D___getitem__(self, *args)
    def __setitem__(self, *args): return _ADMM.LinOpVector2D___setitem__(self, *args)
    def append(self, *args): return _ADMM.LinOpVector2D_append(self, *args)
    def empty(self): return _ADMM.LinOpVector2D_empty(self)
    def size(self): return _ADMM.LinOpVector2D_size(self)
    def clear(self): return _ADMM.LinOpVector2D_clear(self)
    def swap(self, *args): return _ADMM.LinOpVector2D_swap(self, *args)
    def get_allocator(self): return _ADMM.LinOpVector2D_get_allocator(self)
    def begin(self): return _ADMM.LinOpVector2D_begin(self)
    def end(self): return _ADMM.LinOpVector2D_end(self)
    def rbegin(self): return _ADMM.LinOpVector2D_rbegin(self)
    def rend(self): return _ADMM.LinOpVector2D_rend(self)
    def pop_back(self): return _ADMM.LinOpVector2D_pop_back(self)
    def erase(self, *args): return _ADMM.LinOpVector2D_erase(self, *args)
    def __init__(self, *args): 
        this = _ADMM.new_LinOpVector2D(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _ADMM.LinOpVector2D_push_back(self, *args)
    def front(self): return _ADMM.LinOpVector2D_front(self)
    def back(self): return _ADMM.LinOpVector2D_back(self)
    def assign(self, *args): return _ADMM.LinOpVector2D_assign(self, *args)
    def resize(self, *args): return _ADMM.LinOpVector2D_resize(self, *args)
    def insert(self, *args): return _ADMM.LinOpVector2D_insert(self, *args)
    def reserve(self, *args): return _ADMM.LinOpVector2D_reserve(self, *args)
    def capacity(self): return _ADMM.LinOpVector2D_capacity(self)
    __swig_destroy__ = _ADMM.delete_LinOpVector2D
    __del__ = lambda self : None;
LinOpVector2D_swigregister = _ADMM.LinOpVector2D_swigregister
LinOpVector2D_swigregister(LinOpVector2D)

class Solution(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Solution, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Solution, name)
    __repr__ = _swig_repr
    def iterator(self): return _ADMM.Solution_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _ADMM.Solution___nonzero__(self)
    def __bool__(self): return _ADMM.Solution___bool__(self)
    def __len__(self): return _ADMM.Solution___len__(self)
    def __iter__(self): return self.key_iterator()
    def iterkeys(self): return self.key_iterator()
    def itervalues(self): return self.value_iterator()
    def iteritems(self): return self.iterator()
    def __getitem__(self, *args): return _ADMM.Solution___getitem__(self, *args)
    def __delitem__(self, *args): return _ADMM.Solution___delitem__(self, *args)
    def has_key(self, *args): return _ADMM.Solution_has_key(self, *args)
    def keys(self): return _ADMM.Solution_keys(self)
    def values(self): return _ADMM.Solution_values(self)
    def items(self): return _ADMM.Solution_items(self)
    def __contains__(self, *args): return _ADMM.Solution___contains__(self, *args)
    def key_iterator(self): return _ADMM.Solution_key_iterator(self)
    def value_iterator(self): return _ADMM.Solution_value_iterator(self)
    def __setitem__(self, *args): return _ADMM.Solution___setitem__(self, *args)
    def asdict(self): return _ADMM.Solution_asdict(self)
    def __init__(self, *args): 
        this = _ADMM.new_Solution(*args)
        try: self.this.append(this)
        except: self.this = this
    def empty(self): return _ADMM.Solution_empty(self)
    def size(self): return _ADMM.Solution_size(self)
    def clear(self): return _ADMM.Solution_clear(self)
    def swap(self, *args): return _ADMM.Solution_swap(self, *args)
    def get_allocator(self): return _ADMM.Solution_get_allocator(self)
    def begin(self): return _ADMM.Solution_begin(self)
    def end(self): return _ADMM.Solution_end(self)
    def rbegin(self): return _ADMM.Solution_rbegin(self)
    def rend(self): return _ADMM.Solution_rend(self)
    def count(self, *args): return _ADMM.Solution_count(self, *args)
    def erase(self, *args): return _ADMM.Solution_erase(self, *args)
    def find(self, *args): return _ADMM.Solution_find(self, *args)
    def lower_bound(self, *args): return _ADMM.Solution_lower_bound(self, *args)
    def upper_bound(self, *args): return _ADMM.Solution_upper_bound(self, *args)
    __swig_destroy__ = _ADMM.delete_Solution
    __del__ = lambda self : None;
Solution_swigregister = _ADMM.Solution_swigregister
Solution_swigregister(Solution)

class SolutionVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SolutionVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SolutionVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _ADMM.SolutionVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _ADMM.SolutionVector___nonzero__(self)
    def __bool__(self): return _ADMM.SolutionVector___bool__(self)
    def __len__(self): return _ADMM.SolutionVector___len__(self)
    def pop(self): return _ADMM.SolutionVector_pop(self)
    def __getslice__(self, *args): return _ADMM.SolutionVector___getslice__(self, *args)
    def __setslice__(self, *args): return _ADMM.SolutionVector___setslice__(self, *args)
    def __delslice__(self, *args): return _ADMM.SolutionVector___delslice__(self, *args)
    def __delitem__(self, *args): return _ADMM.SolutionVector___delitem__(self, *args)
    def __getitem__(self, *args): return _ADMM.SolutionVector___getitem__(self, *args)
    def __setitem__(self, *args): return _ADMM.SolutionVector___setitem__(self, *args)
    def append(self, *args): return _ADMM.SolutionVector_append(self, *args)
    def empty(self): return _ADMM.SolutionVector_empty(self)
    def size(self): return _ADMM.SolutionVector_size(self)
    def clear(self): return _ADMM.SolutionVector_clear(self)
    def swap(self, *args): return _ADMM.SolutionVector_swap(self, *args)
    def get_allocator(self): return _ADMM.SolutionVector_get_allocator(self)
    def begin(self): return _ADMM.SolutionVector_begin(self)
    def end(self): return _ADMM.SolutionVector_end(self)
    def rbegin(self): return _ADMM.SolutionVector_rbegin(self)
    def rend(self): return _ADMM.SolutionVector_rend(self)
    def pop_back(self): return _ADMM.SolutionVector_pop_back(self)
    def erase(self, *args): return _ADMM.SolutionVector_erase(self, *args)
    def __init__(self, *args): 
        this = _ADMM.new_SolutionVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _ADMM.SolutionVector_push_back(self, *args)
    def front(self): return _ADMM.SolutionVector_front(self)
    def back(self): return _ADMM.SolutionVector_back(self)
    def assign(self, *args): return _ADMM.SolutionVector_assign(self, *args)
    def resize(self, *args): return _ADMM.SolutionVector_resize(self, *args)
    def insert(self, *args): return _ADMM.SolutionVector_insert(self, *args)
    def reserve(self, *args): return _ADMM.SolutionVector_reserve(self, *args)
    def capacity(self): return _ADMM.SolutionVector_capacity(self)
    __swig_destroy__ = _ADMM.delete_SolutionVector
    __del__ = lambda self : None;
SolutionVector_swigregister = _ADMM.SolutionVector_swigregister
SolutionVector_swigregister(SolutionVector)

class IntPair(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IntPair, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IntPair, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _ADMM.new_IntPair(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_setmethods__["first"] = _ADMM.IntPair_first_set
    __swig_getmethods__["first"] = _ADMM.IntPair_first_get
    if _newclass:first = _swig_property(_ADMM.IntPair_first_get, _ADMM.IntPair_first_set)
    __swig_setmethods__["second"] = _ADMM.IntPair_second_set
    __swig_getmethods__["second"] = _ADMM.IntPair_second_get
    if _newclass:second = _swig_property(_ADMM.IntPair_second_get, _ADMM.IntPair_second_set)
    def __len__(self): return 2
    def __repr__(self): return str((self.first, self.second))
    def __getitem__(self, index): 
      if not (index % 2): 
        return self.first
      else:
        return self.second
    def __setitem__(self, index, val):
      if not (index % 2): 
        self.first = val
      else:
        self.second = val
    __swig_destroy__ = _ADMM.delete_IntPair
    __del__ = lambda self : None;
IntPair_swigregister = _ADMM.IntPair_swigregister
IntPair_swigregister(IntPair)

class PairVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, PairVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, PairVector, name)
    __repr__ = _swig_repr
    def iterator(self): return _ADMM.PairVector_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _ADMM.PairVector___nonzero__(self)
    def __bool__(self): return _ADMM.PairVector___bool__(self)
    def __len__(self): return _ADMM.PairVector___len__(self)
    def pop(self): return _ADMM.PairVector_pop(self)
    def __getslice__(self, *args): return _ADMM.PairVector___getslice__(self, *args)
    def __setslice__(self, *args): return _ADMM.PairVector___setslice__(self, *args)
    def __delslice__(self, *args): return _ADMM.PairVector___delslice__(self, *args)
    def __delitem__(self, *args): return _ADMM.PairVector___delitem__(self, *args)
    def __getitem__(self, *args): return _ADMM.PairVector___getitem__(self, *args)
    def __setitem__(self, *args): return _ADMM.PairVector___setitem__(self, *args)
    def append(self, *args): return _ADMM.PairVector_append(self, *args)
    def empty(self): return _ADMM.PairVector_empty(self)
    def size(self): return _ADMM.PairVector_size(self)
    def clear(self): return _ADMM.PairVector_clear(self)
    def swap(self, *args): return _ADMM.PairVector_swap(self, *args)
    def get_allocator(self): return _ADMM.PairVector_get_allocator(self)
    def begin(self): return _ADMM.PairVector_begin(self)
    def end(self): return _ADMM.PairVector_end(self)
    def rbegin(self): return _ADMM.PairVector_rbegin(self)
    def rend(self): return _ADMM.PairVector_rend(self)
    def pop_back(self): return _ADMM.PairVector_pop_back(self)
    def erase(self, *args): return _ADMM.PairVector_erase(self, *args)
    def __init__(self, *args): 
        this = _ADMM.new_PairVector(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _ADMM.PairVector_push_back(self, *args)
    def front(self): return _ADMM.PairVector_front(self)
    def back(self): return _ADMM.PairVector_back(self)
    def assign(self, *args): return _ADMM.PairVector_assign(self, *args)
    def resize(self, *args): return _ADMM.PairVector_resize(self, *args)
    def insert(self, *args): return _ADMM.PairVector_insert(self, *args)
    def reserve(self, *args): return _ADMM.PairVector_reserve(self, *args)
    def capacity(self): return _ADMM.PairVector_capacity(self)
    __swig_destroy__ = _ADMM.delete_PairVector
    __del__ = lambda self : None;
PairVector_swigregister = _ADMM.PairVector_swigregister
PairVector_swigregister(PairVector)

class PairVector2D(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, PairVector2D, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, PairVector2D, name)
    __repr__ = _swig_repr
    def iterator(self): return _ADMM.PairVector2D_iterator(self)
    def __iter__(self): return self.iterator()
    def __nonzero__(self): return _ADMM.PairVector2D___nonzero__(self)
    def __bool__(self): return _ADMM.PairVector2D___bool__(self)
    def __len__(self): return _ADMM.PairVector2D___len__(self)
    def pop(self): return _ADMM.PairVector2D_pop(self)
    def __getslice__(self, *args): return _ADMM.PairVector2D___getslice__(self, *args)
    def __setslice__(self, *args): return _ADMM.PairVector2D___setslice__(self, *args)
    def __delslice__(self, *args): return _ADMM.PairVector2D___delslice__(self, *args)
    def __delitem__(self, *args): return _ADMM.PairVector2D___delitem__(self, *args)
    def __getitem__(self, *args): return _ADMM.PairVector2D___getitem__(self, *args)
    def __setitem__(self, *args): return _ADMM.PairVector2D___setitem__(self, *args)
    def append(self, *args): return _ADMM.PairVector2D_append(self, *args)
    def empty(self): return _ADMM.PairVector2D_empty(self)
    def size(self): return _ADMM.PairVector2D_size(self)
    def clear(self): return _ADMM.PairVector2D_clear(self)
    def swap(self, *args): return _ADMM.PairVector2D_swap(self, *args)
    def get_allocator(self): return _ADMM.PairVector2D_get_allocator(self)
    def begin(self): return _ADMM.PairVector2D_begin(self)
    def end(self): return _ADMM.PairVector2D_end(self)
    def rbegin(self): return _ADMM.PairVector2D_rbegin(self)
    def rend(self): return _ADMM.PairVector2D_rend(self)
    def pop_back(self): return _ADMM.PairVector2D_pop_back(self)
    def erase(self, *args): return _ADMM.PairVector2D_erase(self, *args)
    def __init__(self, *args): 
        this = _ADMM.new_PairVector2D(*args)
        try: self.this.append(this)
        except: self.this = this
    def push_back(self, *args): return _ADMM.PairVector2D_push_back(self, *args)
    def front(self): return _ADMM.PairVector2D_front(self)
    def back(self): return _ADMM.PairVector2D_back(self)
    def assign(self, *args): return _ADMM.PairVector2D_assign(self, *args)
    def resize(self, *args): return _ADMM.PairVector2D_resize(self, *args)
    def insert(self, *args): return _ADMM.PairVector2D_insert(self, *args)
    def reserve(self, *args): return _ADMM.PairVector2D_reserve(self, *args)
    def capacity(self): return _ADMM.PairVector2D_capacity(self)
    __swig_destroy__ = _ADMM.delete_PairVector2D
    __del__ = lambda self : None;
PairVector2D_swigregister = _ADMM.PairVector2D_swigregister
PairVector2D_swigregister(PairVector2D)

# This file is compatible with both classic and new-style classes.


